name: Pull requests check pipeline

on: 
  pull_request:
    branches: [main]

permissions:
    contents: read
    id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.10.0"
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v6
          with:
            role-to-assume: ${{ vars.AWS_ROLE_ARN}}
            aws-region: ${{ vars.AWS_REGION}}

        - name: Terraform format check
          run: terraform fmt -check -recusive

        - name: Terraform init
          run: terraform init -lockfile=readonly
          
        - name: Terraform validate
          run : terraform validate

        - name: Terraform plan
          run: terraform plan

    

    